/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Categories.GET.GetCategoriesResponseDto"][];
                        "application/json": components["schemas"]["Categories.GET.GetCategoriesResponseDto"][];
                        "text/json": components["schemas"]["Categories.GET.GetCategoriesResponseDto"][];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                        "application/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                        "text/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Categories._Slug.GET.GetCategoryBySlugResponseDto"];
                        "application/json": components["schemas"]["Categories._Slug.GET.GetCategoryBySlugResponseDto"];
                        "text/json": components["schemas"]["Categories._Slug.GET.GetCategoryBySlugResponseDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                        "application/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                        "text/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Products._Slug.GET.GetProductBySlugResponseDto"];
                        "application/json": components["schemas"]["Products._Slug.GET.GetProductBySlugResponseDto"];
                        "text/json": components["schemas"]["Products._Slug.GET.GetProductBySlugResponseDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                        "application/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                        "text/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{slug}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    page: number;
                    pageSize?: number;
                    sort?: string;
                    filter?: string;
                };
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Products._Slug.Reviews.GET.GetReviewsByProductSlugResponseDto"][];
                        "application/json": components["schemas"]["Products._Slug.Reviews.GET.GetReviewsByProductSlugResponseDto"][];
                        "text/json": components["schemas"]["Products._Slug.Reviews.GET.GetReviewsByProductSlugResponseDto"][];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                        "application/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                        "text/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Settings.GET.GetSettingsResponseDto"];
                        "application/json": components["schemas"]["Settings.GET.GetSettingsResponseDto"];
                        "text/json": components["schemas"]["Settings.GET.GetSettingsResponseDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                        "application/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                        "text/json": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "Categories.GET.GetCategoriesResponseDto": {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            parentId?: string | null;
            name: string;
            slug: string;
            description?: string | null;
        };
        "Categories._Slug.GET.GetCategoryBySlugResponseDto": {
            name: string;
            slug: string;
            description?: string | null;
            products: components["schemas"]["Categories._Slug.GET.GetCategoryBySlugResponseDto.Product"][];
            subcategories: components["schemas"]["Categories._Slug.GET.GetCategoryBySlugResponseDto.Subcategory"][];
        };
        "Categories._Slug.GET.GetCategoryBySlugResponseDto.Product": {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            /** Format: int32 */
            allowance: number;
            tags?: string[] | null;
            /** Format: date-time */
            releaseDate: string;
            rating: components["schemas"]["Categories._Slug.GET.GetCategoryBySlugResponseDto.Product.ProductRating"];
            attributes: components["schemas"]["Categories._Slug.GET.GetCategoryBySlugResponseDto.Product.AttributeOrder"][];
            images: components["schemas"]["Categories._Slug.GET.GetCategoryBySlugResponseDto.Product.Image"][];
            variants: components["schemas"]["Categories._Slug.GET.GetCategoryBySlugResponseDto.Product.Variant"][];
        };
        "Categories._Slug.GET.GetCategoryBySlugResponseDto.Product.AttributeOrder": {
            name: string;
            title: string;
            /** Format: int32 */
            position: number;
        };
        "Categories._Slug.GET.GetCategoryBySlugResponseDto.Product.Image": {
            /** Format: uuid */
            id: string;
            src: string;
            alt: string;
            /** Format: int32 */
            position: number;
        };
        "Categories._Slug.GET.GetCategoryBySlugResponseDto.Product.ProductRating": {
            /** Format: double */
            average: number;
            /** Format: int32 */
            total: number;
            quantities: components["schemas"]["Categories._Slug.GET.GetCategoryBySlugResponseDto.Product.ProductRating.RatingQuantities"];
        };
        "Categories._Slug.GET.GetCategoryBySlugResponseDto.Product.ProductRating.RatingQuantities": {
            /** Format: int32 */
            1: number;
            /** Format: int32 */
            2: number;
            /** Format: int32 */
            3: number;
            /** Format: int32 */
            4: number;
            /** Format: int32 */
            5: number;
        };
        "Categories._Slug.GET.GetCategoryBySlugResponseDto.Product.Variant": {
            /** Format: uuid */
            id: string;
            name: string;
            sku: string;
            canSubscribe?: boolean | null;
            /** Format: double */
            priceCurrent: number;
            /** Format: double */
            priceBase: number;
            /** Format: double */
            subscriptionDiscountPercentage?: number | null;
            /** Format: int32 */
            stock: number;
            /** Format: int32 */
            allowanceOverride?: number | null;
            active: boolean;
            /** Format: date-time */
            releaseDate: string;
            attributes: components["schemas"]["Categories._Slug.GET.GetCategoryBySlugResponseDto.Product.Variant.Attribute"][];
            images: components["schemas"]["Categories._Slug.GET.GetCategoryBySlugResponseDto.Product.Variant.Image"][];
        };
        "Categories._Slug.GET.GetCategoryBySlugResponseDto.Product.Variant.Attribute": {
            type: components["schemas"]["Categories._Slug.GET.GetCategoryBySlugResponseDto.Product.Variant.Attribute.AttributeType"];
            value: components["schemas"]["Categories._Slug.GET.GetCategoryBySlugResponseDto.Product.Variant.Attribute.AttributeValue"];
        };
        "Categories._Slug.GET.GetCategoryBySlugResponseDto.Product.Variant.Attribute.AttributeType": {
            /** Format: uuid */
            id: string;
            name: string;
            title: string;
        };
        "Categories._Slug.GET.GetCategoryBySlugResponseDto.Product.Variant.Attribute.AttributeValue": {
            code: string;
            name: string;
            /** Format: int32 */
            position: number;
        };
        "Categories._Slug.GET.GetCategoryBySlugResponseDto.Product.Variant.Image": {
            /** Format: uuid */
            id: string;
            src: string;
            alt: string;
            /** Format: int32 */
            position: number;
        };
        "Categories._Slug.GET.GetCategoryBySlugResponseDto.Subcategory": {
            name: string;
            slug: string;
            description?: string | null;
        };
        "Microsoft.AspNetCore.Http.HttpValidationProblemDetails": components["schemas"]["Microsoft.AspNetCore.Mvc.ProblemDetails"] & ({
            errors?: {
                [key: string]: string[];
            };
        } & {
            [key: string]: unknown;
        });
        "Microsoft.AspNetCore.Mvc.ProblemDetails": {
            type?: string | null;
            title?: string | null;
            /** Format: int32 */
            status?: number | null;
            detail?: string | null;
            instance?: string | null;
        } & {
            [key: string]: unknown;
        };
        "Products._Slug.GET.GetProductBySlugResponseDto": {
            /** Format: uuid */
            id: string;
            name: string;
            description?: string | null;
            slug: string;
            /** Format: int32 */
            allowance: number;
            tags?: string[] | null;
            /** Format: date-time */
            releaseDate: string;
            collections: components["schemas"]["Products._Slug.GET.GetProductBySlugResponseDto.Collection"][];
            attributes: components["schemas"]["Products._Slug.GET.GetProductBySlugResponseDto.AttributeOrder"][];
            categories: components["schemas"]["Products._Slug.GET.GetProductBySlugResponseDto.Category"][];
            details: components["schemas"]["Products._Slug.GET.GetProductBySlugResponseDto.Detail"][];
            images: components["schemas"]["Products._Slug.GET.GetProductBySlugResponseDto.Image"][];
            rating: components["schemas"]["Products._Slug.GET.GetProductBySlugResponseDto.ProductRating"];
            reviews: components["schemas"]["Products._Slug.GET.GetProductBySlugResponseDto.Review"][];
            variants: components["schemas"]["Products._Slug.GET.GetProductBySlugResponseDto.Variant"][];
        };
        "Products._Slug.GET.GetProductBySlugResponseDto.AttributeOrder": {
            name: string;
            title: string;
            /** Format: int32 */
            position: number;
        };
        "Products._Slug.GET.GetProductBySlugResponseDto.Category": {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            parentId?: string | null;
            name: string;
            slug: string;
            description?: string | null;
        };
        "Products._Slug.GET.GetProductBySlugResponseDto.Collection": {
            /** Format: uuid */
            id: string;
            name: string;
            title: string;
            description?: string | null;
            slug: string;
            products: components["schemas"]["Products._Slug.GET.GetProductBySlugResponseDto.Collection.Product"][];
        };
        "Products._Slug.GET.GetProductBySlugResponseDto.Collection.Product": {
            /** Format: uuid */
            id: string;
            name?: string | null;
            slug: string;
            /** Format: int32 */
            position: number;
            images: components["schemas"]["Products._Slug.GET.GetProductBySlugResponseDto.Image"][];
        };
        "Products._Slug.GET.GetProductBySlugResponseDto.Detail": {
            /** Format: uuid */
            id: string;
            name: string;
            value: string;
        };
        "Products._Slug.GET.GetProductBySlugResponseDto.Image": {
            /** Format: uuid */
            id: string;
            src: string;
            alt: string;
            /** Format: int32 */
            position: number;
        };
        "Products._Slug.GET.GetProductBySlugResponseDto.ProductRating": {
            /** Format: double */
            average: number;
            /** Format: int32 */
            total: number;
            quantities: components["schemas"]["Products._Slug.GET.GetProductBySlugResponseDto.ProductRating.RatingQuantities"];
        };
        "Products._Slug.GET.GetProductBySlugResponseDto.ProductRating.RatingQuantities": {
            /** Format: int32 */
            1: number;
            /** Format: int32 */
            2: number;
            /** Format: int32 */
            3: number;
            /** Format: int32 */
            4: number;
            /** Format: int32 */
            5: number;
        };
        "Products._Slug.GET.GetProductBySlugResponseDto.Review": {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            variantId?: string | null;
            title?: string | null;
            description: string;
            /** Format: int32 */
            rating: number;
            /** Format: date-time */
            createdAt: string;
        };
        "Products._Slug.GET.GetProductBySlugResponseDto.Variant": {
            /** Format: uuid */
            id: string;
            name: string;
            sku: string;
            canSubscribe?: boolean | null;
            /** Format: double */
            priceCurrent: number;
            /** Format: double */
            priceBase: number;
            /** Format: double */
            subscriptionDiscountPercentage?: number | null;
            /** Format: int32 */
            stock: number;
            /** Format: int32 */
            allowanceOverride?: number | null;
            active: boolean;
            /** Format: date-time */
            releaseDate: string;
            attributes: components["schemas"]["Products._Slug.GET.GetProductBySlugResponseDto.Variant.Attribute"][];
            details: components["schemas"]["Products._Slug.GET.GetProductBySlugResponseDto.Variant.Detail"][];
            images: components["schemas"]["Products._Slug.GET.GetProductBySlugResponseDto.Variant.Image"][];
        };
        "Products._Slug.GET.GetProductBySlugResponseDto.Variant.Attribute": {
            type: components["schemas"]["Products._Slug.GET.GetProductBySlugResponseDto.Variant.Attribute.AttributeType"];
            value: components["schemas"]["Products._Slug.GET.GetProductBySlugResponseDto.Variant.Attribute.AttributeValue"];
        };
        "Products._Slug.GET.GetProductBySlugResponseDto.Variant.Attribute.AttributeType": {
            /** Format: uuid */
            id: string;
            name: string;
            title: string;
        };
        "Products._Slug.GET.GetProductBySlugResponseDto.Variant.Attribute.AttributeValue": {
            code: string;
            name: string;
            /** Format: int32 */
            position: number;
        };
        "Products._Slug.GET.GetProductBySlugResponseDto.Variant.Detail": {
            /** Format: uuid */
            id: string;
            name: string;
            value: string;
        };
        "Products._Slug.GET.GetProductBySlugResponseDto.Variant.Image": {
            /** Format: uuid */
            id: string;
            src: string;
            alt: string;
            /** Format: int32 */
            position: number;
        };
        "Products._Slug.Reviews.GET.GetReviewsByProductSlugResponseDto": {
            title?: string | null;
            description: string;
            /** Format: int32 */
            rating: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt?: string | null;
            variant?: components["schemas"]["Products._Slug.Reviews.GET.GetReviewsByProductSlugResponseDto.ProductVariant"] | null;
        };
        "Products._Slug.Reviews.GET.GetReviewsByProductSlugResponseDto.ProductVariant": {
            name: string;
            sku: string;
        };
        "Settings.GET.GetSettingsResponseDto": {
            /** Format: double */
            baseExpressDeliveryCost: number;
            /** Format: double */
            freeExpressDeliveryThreshold: number;
            /** Format: int32 */
            lowStockThreshold: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
