import { CSSProperties } from "react";

export type BlendData = {
    code: string;
    name: string;
    origins: string[];
    description: string;
    notes: string;
    pairings: string;
    intensity: number;
    acidity: "Low" | "Medium" | "High";
    roast: "Light" | "Medium" | "Dark" | "Extra Dark";
    colors: { main: CSSProperties["color"] };
};

export const blendData: BlendData[] = [
    {
        code: "HO",
        name: "House",
        origins: ["br", "co"],
        description: "A balanced, everyday blend designed for consistency and approachability.",
        notes: "Milk chocolate, toasted nuts, subtle caramel.",
        pairings: "Ideal with breakfast pastries, biscuits, or enjoyed black.",
        intensity: 7,
        acidity: "Medium",
        roast: "Medium",
        colors: { main: "#FFD1A6" },
    },
    {
        code: "LT",
        name: "Light",
        origins: ["et", "ke"],
        description:
            "Bright and vibrant, highlighting the natural character of lightly roasted beans.",
        notes: "Citrus, floral notes, honey.",
        pairings: "Pairs well with fruit, yoghurt, and light breakfasts.",
        intensity: 4,
        acidity: "High",
        roast: "Light",
        colors: { main: "#E7A67A" },
    },
    {
        code: "MD",
        name: "Medium",
        origins: ["co", "gt"],
        description: "A well-rounded roast balancing acidity, sweetness, and body.",
        notes: "Milk chocolate, red apple, almond.",
        pairings: "Great with baked goods or enjoyed on its own.",
        intensity: 6,
        acidity: "Medium",
        roast: "Medium",
        colors: { main: "#945A38" },
    },
    {
        code: "DK",
        name: "Dark",
        origins: ["br", "id"],
        description: "A bold, rich roast with a deep and warming profile.",
        notes: "Dark chocolate, roasted nuts, spice.",
        pairings: "Complements chocolate desserts and rich foods.",
        intensity: 9,
        acidity: "Low",
        roast: "Dark",
        colors: { main: "#634433" },
    },
    {
        code: "XD",
        name: "Extra Dark",
        origins: ["id", "vn"],
        description: "An intensely roasted blend for those who prefer a strong, smoky cup.",
        notes: "Smoky cocoa, charred wood, bittersweet finish.",
        pairings: "Best with milk-based drinks or strong desserts.",
        intensity: 12,
        acidity: "Low",
        roast: "Extra Dark",
        colors: { main: "#412929" },
    },
    {
        code: "BK",
        name: "Breakfast",
        origins: ["br", "hn"],
        description: "Smooth and mellow, crafted for an easy start to the day.",
        notes: "Soft caramel, biscuit, mild citrus.",
        pairings: "Perfect with toast, cereals, and light meals.",
        intensity: 5,
        acidity: "Medium",
        roast: "Medium",
        colors: { main: "#EBC3AB" },
    },
    {
        code: "PK",
        name: "Pumpkin Spice",
        origins: ["br"],
        description:
            "A seasonal blend infused with warm autumn spices; most commonly enjoyed as a latte.",
        notes: "Pumpkin spice, cinnamon, nutmeg, vanilla.",
        pairings: "Pairs beautifully with sweet pastries and desserts.",
        intensity: 6,
        acidity: "Low",
        roast: "Medium",
        colors: { main: "#DDA774" },
    },
    {
        code: "MO",
        name: "Mocha",
        origins: ["br", "pe"],
        description: "A rich blend with natural cocoa tones for chocolate lovers.",
        notes: "Cocoa, dark chocolate, roasted nuts.",
        pairings: "Ideal with chocolate desserts or as a mocha-style drink.",
        intensity: 7,
        acidity: "Low",
        roast: "Medium",
        colors: { main: "#7C624A" },
    },
    {
        code: "ES",
        name: "Espresso",
        origins: ["br", "co", "in"],
        description: "Crafted for espresso extraction with depth, balance, and crema.",
        notes: "Dark chocolate, brown sugar, subtle spice.",
        pairings: "Excellent alone or with milk-based drinks.",
        intensity: 10,
        acidity: "Low",
        roast: "Dark",
        colors: { main: "#572D2C" },
    },
    {
        code: "VA",
        name: "Vanilla",
        origins: ["br"],
        description: "Smooth and lightly sweet with a natural vanilla aroma.",
        notes: "Vanilla, cream, soft caramel.",
        pairings: "Pairs well with desserts or enjoyed as a latte.",
        intensity: 5,
        acidity: "Low",
        roast: "Medium",
        colors: { main: "#AE8EC9" },
    },
    {
        code: "CA",
        name: "Caramel",
        origins: ["br", "co"],
        description: "A comforting blend with buttery sweetness.",
        notes: "Caramel, toffee, roasted nuts.",
        pairings: "Great with sweet pastries and milk-based drinks.",
        intensity: 6,
        acidity: "Low",
        roast: "Medium",
        colors: { main: "#E4AB60" },
    },
    {
        code: "IN",
        name: "Intense",
        origins: ["id", "br"],
        description: "High-impact flavour with extra body and low acidity.",
        notes: "Dark cocoa, molasses, roasted grain.",
        pairings: "Best suited to strong brews or milk drinks.",
        intensity: 11,
        acidity: "Low",
        roast: "Dark",
        colors: { main: "#F0CF62" },
    },
    {
        code: "FR",
        name: "French Roast",
        origins: ["br", "cr"],
        description: "A classic French-style roast with a smoky, full-bodied character.",
        notes: "Smoky cocoa, charred sugar, bold finish.",
        pairings: "Pairs well with rich desserts or cream.",
        intensity: 12,
        acidity: "Low",
        roast: "Extra Dark",
        colors: { main: "#9BDBD6" },
    },
    {
        code: "IR",
        name: "Italian Roast",
        origins: ["br", "in"],
        description: "Deeply roasted for a traditional Italian espresso experience.",
        notes: "Burnt caramel, dark chocolate, smoke.",
        pairings: "Perfect for short espresso shots and milk drinks.",
        intensity: 13,
        acidity: "Low",
        roast: "Extra Dark",
        colors: { main: "#89D687" },
    },
];
